#!/bin/bash
function process_script_request {
  if [[ $# -eq 0 ]]; then
    show_help
  else
    case $1 in
      help) show_help;;
      sails) serve_backend;;
      ng) update_and_watch_assets;;
      logs) show_logs;;
      deploy) deploy_app;;
      deploy:test) deploy_test_app;;
    esac
  fi
}

function show_help {
  echo "What to do?"
  echo "help  sails  ng   logs  deploy  deploy:test"
}

function serve_backend {
  sails lift
}

function update_and_watch_assets {
  cd angular
  ng build --watch --extract-css
  cd ../
}

function show_logs {
  heroku logs --tail --app online-tutoring
}

function deploy_app {
  build_assets_for_deployment
  git co production
  git merge master
  git push
  git co master
}

function build_assets_for_deployment {
  cd angular
  ng build --prod --extract-css --output-path ../assets
  git add assets
  git commit -m "updating assets for deployment"
  cd ../
}

function deploy_test_app {
  git push -f heroku-test master
}

process_script_request $1