#!/bin/bash
function process_script_request {
  if [[ $# -eq 0 ]]; then
    show_help
  else
    case $1 in
      help) show_help;;
      sails) start_server;;
      ng) build_and_watch_assets;;
      ng:build) build_assets;;
      logs) show_logs;;
      deploy) deploy_app;;
      deploy:test) deploy_test_app;;
    esac
  fi
}

function show_help {
  echo "What to do?"
  echo "help  sails  ng  ng:build  logs  deploy  deploy:test"
}

function start_server {
  sails lift
}

function build_assets {
  cd angular
  ng build --extract-css
  cd ../
}

function build_and_watch_assets {
  cd angular
  ng build --watch --extract-css
  cd ../
}

function show_logs {
  heroku logs --tail --app online-tutoring
}

function deploy_app {
  git co production
  git merge master
  git push
  git co master
}

function deploy_test_app {
  git push -f heroku-test master
}

process_script_request $1